from enum import Enum

# This file imports or defines enumerations for use across the plugin
from .toolkitData.SiacFields import SiacField
from .toolkitData.SiacDataLayerTypes import DataLayer
from .toolkitData.SiacIndicators import SiacIndicator
from .toolkitData.SiacTcacClasses import TreePatternConfiguration
from .toolkitData.SiacEntities import SiacEntity


# Tool 
class SiacToolkitModule(Enum):
    TCAC = "TCAC"
    SITA = "SITA"
    TOPOMOD = "TOPOMOD"
    COIN = "COIN"
    DATA_PROCESSOR = "DATA PROCESSOR"
    MAP_PERIMETER_TOOL = "PERIMETER"
    
class SiacGeometryType(Enum):
    POINT = "point"
    POLYGON = "polygon"

class SiacToolkitDataType(Enum):
    LOCAL_COOLING_POTENTIAL_DATA = "CoolingPotentialData"
    GRAPH = "Graph" 
    RICHNESS_AND_DIVERSITY_ASSESSMENT = "Diversity"
    NEAR_LAYER = "Shortest Lines Layer"
    TALLO_DB = "DB-Tallo"
    URBAN_TREE_DB = "UTDB"

# Topology Rule Templates
class TopologyRule(Enum):
    TOUCHES = 1
    CONTAINS = 2
    INTERSECTS = 3
    CROSSES = 4
    WITHIN = 5
    OVERLAPS = 6

# Statistical parameters implemented for reporting
class DescriptiveParameter(Enum):
    AVERAGE = "average"
    SUM = "sum"


class TcacTask(Enum):
    MODEL_TREE_COVER = 0
    TREE_PATTERN_ASSESSMENT_AND_CLASSIFICATION = 1
    MODEL_TRAITS_FROM_TALLO = 2
    MODEL_TRAITS_FROM_UTDB = 3


# Tasks for Data processor 
class DataProcessorTask(Enum):
    COMPUTE_STREET_MORPHOLOGY = 0
    COMPUTE_CLOSED_TESSELLATION = 1

# Tasks for TOPOMOD 
class TopomodTask(Enum):
    COMPUTE_TOPOLOGY = 1
    COMPUTE_NEAREST_NEIGHBOUR_NETWORK = 2
    COMPUTE_CONNECTIVITY = 3
    ASSESS_FRAGMENTATION = 4

class SitaTask(Enum):
    ITERATE_PLOTS = 1
    ITERATE_SAMPLED_LOCATIONS = 2

# Map Canvas Tools
class MapCanvasTools(Enum):
    LOCALIZER_TOOL = 0

# Regression predictors 
class LocalRegressionConverType(Enum):
    USE_AREA = "Predict on area of cover"
    USE_SHARE = "Predict on share of cover"

class LstRegressionPredictorSet(Enum):
    INCLUDE_IMPV_AS_SINGLE = "Include impervious cover as single entity"
    INCLUDE_IMPV_AS_MULTIPLE = "Include impervious cover as individual entities"
    EXCLUDE_IMPV = "Exclude impervious cover"


class CoinForestCoverIdentificationEngine(Enum):
    SITE_SPECIFIC_TRAITS = "Site-level"
    SELF_REFERENTIAL = "Self-referential"

class SiacToolkitOptionValue(Enum):
    TCAC_PARAMS_USER_DEFINED_TREE_CROWN_DIAMETER = "USER_DEFINED_CROWN_DIAMETER"
    TCAC_PARAMS_SPECIES_FIELDNAME = "TREE_GENUS_FIELDNAME"
    TCAC_PARAMS_TREE_CROWN_DIAMETER_VALUE = "TREE_CROWN_DIAMETER"
    TCAC_PARAMS_TREE_CROWN_DIAMETER_FIELDNAME = "TREE_CROWN_DIAMETER_FIELD"
    TCAC_PARAMS_FRUITTREE_SPECIES_LIST = "FRUIT_TREE_GENUS_LIST"
    TCAC_PARAMS_TREE_HEALTH_FIELDNAME = "TREE_HEALTH_FIELD"
    TCAC_PARAMS_ASSESS_TREE_ESS_SCALING = "TREE_ESS_MEDIATION"
    DATAPROCESSOR_PARAMS_STREET_WIDTH = "STREET_WIDTH"
    CONNECTIVITY_PARAMS_NEIGHBOUR_COUNT = "NEIGHBOUR_COUNT"
    CONNECTIVITY_PARAMS_THRESHOLD = "CONNECTIVITY_THRESHOLD"
    CONNECTIVITY_INDICATORS_BETWEENNESS = "BETWEENNESS"
    CONNECTIVITY_INDICATORS_CLOSENESS = "CLOSENESS"
    CONNECTIVITY_INDICATORS_DEGREE_CENTRALITY = "DEGREE_CENTRALITY"
    CONNECTIVITY_INDICATORS_COMPONENT_DIAMETER = "DIAMETER"
    CONNECTIVITY_INDICATORS_ECCENTRICITY = "ECCENTRICITY"
    CONNECTIVITY_PARAMS_BUILDINGS_AS_BARRIERS = "BUILDINGS_AS_BARRIERS"
    CONNECTIVITY_PARAMS_ANCHOR_POINT = "ANCHOR_POINT"
    CONNECTIVITY_PARAMS_FRAGMENTATION_DISTANCES = "FRAGMENTATION_DISTANCES"
    SITA_PARAMS_SAMPLE_SIZE = "SITA_SAMPLE_SIZE"
    SITA_PARAMS_MIN_PATCHDISTANCE = "SITA_MINIMUM_DISTANCE"
    SITA_PARAMS_PATCHDIAMETER = "SITA_PATCH_DIAMETER"
    COIN_ESS_AIR_QUALITY_SO2_REMOVALRATE = "DEFAULT_SERVICE_POTENTIAL_SO2"
    COIN_ESS_AIR_QUALITY_NO2_REMOVALRATE = "DEFAULT_SERVICE_POTENTIAL_NO2"
    COIN_ESS_AIR_QUALITY_PM10_REMOVALRATE = "DEFAULT_SERVICE_POTENTIAL_PM10"
    COIN_ESS_AIR_QUALITY_O3_REMOVALRATE = "DEFAULT_SERVICE_POTENTIAL_O3"
    COIN_ESS_AIR_QUALITY_CO_REMOVALRATE = "DEFAULT_SERVICE_POTENTIAL_CO"
    COIN_ESS_CARBON_STORAGERATE = "DEFAULT_SERVICE_POTENTIAL_C_STORAGE"
    COIN_ESS_CARBON_SEQUESTRATIONRATE = "DEFAULT_SERVICE_POTENTIAL_C_SEQ"
    COIN_ESS_COOLING_PREDS_COVERTYPE = "LST_REGRESSION_VARTYPE"
    COIN_ESS_COOLING_PREDS_INCLUDE_IMPV = "LST_REGRESSION_PREDICTOR_CHOICE"
    COIN_ESS_COOLING_INCLUDE_ANCILLARY_ENTITIES = "LST_REGRESSION_PREDICTOR_INCLUDE_ANCILLARY"
    COIN_ESS_COOLING_INCLUDE_LOWESS = "LST_REGRESSION_INCLUDE_LOWESS"
    COIN_ESS_MEDIATE_ESS = "COIN_ESS_MEDIATION"
    TYPOLOGY_FOREST_RELATIVE_TREE_COVER_THRESHOLD = "FOREST_RELATIVE_TREE_COVER_THRESHOLD"
    TYPOLOGY_FOREST_MINIMUM_AREA_THRESHOLD = "FOREST_MINIMUM_AREA_THRESHOLD"
    TYPOLOGY_NEAR_THRESHOLD = "NEAR_THRESHOLD"
    TYPOLOGY_LINEARITY_THRESHOLD = "LINEARITY_THRESHOLD"
