# -*- coding: utf-8 -*-
"""
/***************************************************************************
 siac
                                 A QGIS plugin
 Spatial Impact Assessment and Classification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-07
        copyright            : (C) 2022 by Sebastian Scheuer
        email                : sebastian.scheuer@geo.hu-berlin.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load siac class from file siac.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ch_siac import siac
    return siac(iface)
