# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ch_siac_ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import *
from PyQt5 import QtCore, QtGui, QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ch_siac_ui_main.ui'))

class Ui_MainWindow(QtWidgets.QMainWindow, FORM_CLASS):
    
    def __init__(self, parent=None):
        """Constructor."""
        super(Ui_MainWindow, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
